from typing import Any, Iterable, Iterator, TypeVar, Generic
_T = TypeVar("_T")
class tqdm(Iterable[_T], Generic[_T]):
    def __init__(iterable: Iterable[_T], *args: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[_T]: ...
    @property
    def iterable(self) -> Iterator[_T]: ...
